### ISSUE TITLE
display disclaimer and intro text somewhere on the chat welcome page

### ISSUE THREAD

**Issue by GuillaumeTurcotte** [dto-btn/chatbot-frontend#10]
use content we had on the [bot framework composer pilot](https://github.com/dto-btn/OpenAIPoCChatBot2/blob/main/dialogs/Greetings/language-generation/en-us/Greetings.en-us.lg).

**Comment by GuillaumeTurcotte** [comment]
Disclaimer should probably be a popup (use fluent-ui) that is closable, has a link to re-view it on the bottom of the page footer besides feedback link. And stores a cookie so its not redisplayed again after accepting and closing dialog.

**Comment by sanjeeveasparan** [comment]
Finished. Will run it by @GuillaumeTurcotte before closing.
